pullup/pullup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^$', RedirectView.as_view(url='/trainings/', permanent=False), name='index'),
    url(r'^admin/', admin.site.urls),
	url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^trainings/', include('trainings.urls', namespace='trainings')),
]

pullup/trainings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	url(r'^training_session/', views.training_session, name='training_session'),
	url(r'^training_summary/', views.training_summary, name='training_summary'),
	url(r'^goal/$', views.GoalView.as_view(), name='apply_goal'),
	url(r'^register_player/', views.PlayerView.as_view(), name='register_player'),
	url(r'^chart/', views.trainings_chart, name='chart'),
]

pullup/trainings/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import FieldDoesNotExist
from django.db import models
from django.utils import timezone


class Player(User):
	goal = models.IntegerField(blank=True, null=True)
	actual_record = models.IntegerField(blank=True, null=True)

	@property
	def reps_done(self):
		total = 0
		trainings = self.trainings.filter(is_done=True)
		for training in trainings:
			total += training.reps_done
		return total

	@property
	def sessions_done(self):
		sessions = self.trainings.filter(is_done=True).order_by('-done_date')
		return sessions

	@property
	def sessions_done_number(self):
		sessions = self.trainings.filter(is_done=True)
		return len(sessions)

	def get_training_session(self):
		''' Function returning proper training session for player
		:return: TrainingSession object
		'''
		if not self.goal:
			return None
		undone = self.trainings.filter(is_done=False).first()
		if undone:
			return undone
		session = TrainingSession.create(user=self)
		return session


class TrainingSession(models.Model):
	is_done = models.BooleanField(default=False)
	user = models.ForeignKey(Player, related_name='trainings')
	series = models.TextField()
	reps_done = models.PositiveIntegerField(default=0)
	created_date = models.DateTimeField(default=timezone.now)
	done_date = models.DateTimeField(blank=True, null=True)
	completed = models.BooleanField(default=False)
	ratio = models.FloatField(default=1.0)

	@staticmethod
	def generate_series(goal, number_of_series, ratio):
		''' Generate new training series
		:param ratio: float number between 0 and 1 describing level of training plan
		:param number_of_series: integer
		:return: string with numbers splitted by spaces
		'''
		goal = int(ratio * goal)
		serie = int(goal / number_of_series)
		if serie < 1:
			serie = 1
		series = [serie] * number_of_series

		# add difference from rounding
		difference = goal - (serie * number_of_series)
		if difference > 0:
			series[0] += difference
		# return ' '.join(map(str, series))
		return series

	@classmethod
	def create(cls, user):
		''' Generate new session based on history
		'''
		# last_users_training = TrainingSession.objects.filter(user=self.user).order_by('-done_date').first()
		last_users_training = user.trainings.order_by('-done_date').first()

		# check if last training was successfully completed, otherwise make next training easier
		if last_users_training and not last_users_training.completed:
			ratio = 0.5
		else:
			ratio = 1.0
		try:
			series = cls.generate_series(goal=user.goal, number_of_series=4, ratio=ratio)
		except FieldDoesNotExist: #for admin debugging
			series = '10 10 10 10'
		training = cls(user=user, series=series, ratio=ratio)
		return training

pullup/trainings/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import Player


class PlayerForm(UserCreationForm):
	class Meta:
		model = Player
		fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'email', )


class GoalForm(forms.ModelForm):
	goal = forms.IntegerField(label='Your goal', min_value=1, max_value=200)
	actual_record = forms.IntegerField(label='Your actual record', min_value=0, max_value=200)

	def clean(self):
		# check if user set higher goal than actual record
		cleaned_data = super(GoalForm, self).clean()

		actual_record = cleaned_data.get('actual_record')
		goal = cleaned_data.get('goal')
		if goal <= actual_record:
			raise ValidationError('Your record cannot be equal or lower than goal', code='invalid')

	class Meta:
		model = Player
		fields = ('goal', 'actual_record', 'id')

pullup/trainings/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView, UpdateView

from .forms import GoalForm, PlayerForm
from .models import TrainingSession, Player


@login_required
def dashboard(request):
	context = {}
	sessions = request.user.player.sessions_done[:5]
	context.update({'sessions': sessions})
	return render(request, template_name='dashboard.html', context=context)


@login_required
def training_summary(request):
	last_training = request.user.player.trainings.filter(is_done=True).order_by('-done_date').first()
	context = {'last_training': last_training}
	return render(request, template_name='training_summary.html', context=context)


@login_required
def trainings_chart(request):
	trainings_done = request.user.player.trainings.filter(is_done=True).order_by('-done_date')
	context = {'trainings_done': trainings_done}
	return render(request, template_name='chart.html', context=context)


@method_decorator(login_required, name='dispatch')
class GoalView(SuccessMessageMixin, FormView):
	template_name = 'apply_goal.html'
	form_class = GoalForm
	success_url = '/trainings/training_session/'
	success_message = 'Your goal was set'

	def get_form(self):
		return self.form_class(instance=self.request.user.player, **self.get_form_kwargs())

	def form_valid(self, form):
		goal = self.request.POST.get('goal')
		actual_record = self.request.POST.get('actual_record')
		if goal > actual_record * 2:
			self.success_message += ', but remember - it might be too hard to achieve with your current record'
		form.save()
		return super(GoalView, self).form_valid(form)


def process_session(session, request):
	''' Process session with passed data (mark as done etc)
	:param session: TrainingSession object
	:param request: request data
	:return: actualized session
	'''
	if 'reps_done' in request.POST and request.POST.get('reps_done'):
		reps_done = int(request.POST.get('reps_done'))
		# in case of cheating
		if reps_done > request.user.player.goal:
			reps_done = 0
		session.reps_done = reps_done
		session.completed = False
	else:
		session.reps_done = int(request.user.player.goal * session.ratio)
		session.completed = True
	session.is_done = True
	session.done_date = datetime.datetime.now()
	session.save()

	return session


@login_required
def training_session(request):
	context = {}
	session = request.user.player.get_training_session()
	if session is None:
		return GoalView.as_view()(request)
	if request.method == 'POST':
		process_session(session=session, request=request)
		return training_summary(request)
	context.update({'session': session})
	return render(request, template_name='training_session.html', context=context)


class PlayerView(SuccessMessageMixin, FormView):
	template_name = 'register_player.html'
	form_class = PlayerForm
	success_url = '/login'
	success_message = 'Your account was created'

	def form_valid(self, form):
		form.save()
		return super(PlayerView, self).form_valid(form)

pullup/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <!-- CSS Reset -->
    <!--<link rel="stylesheet" href="bower_components/normalize.css/normalize.css">-->

    <!-- Milligram CSS minified -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.2.4/milligram.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container">
    <h2>your personal pullups trainer</h2>
    {% if messages %}
    <blockquote>
        {% for message in messages %}
        <p><em>{{ message }}</em></p>
        {% endfor %}
    </blockquote>
    {% endif %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}
</div>
</body>
</html>

pullup/trainings/templates/apply_goal.html
{% extends "dashboard_base.html" %}
{% block menu %}
    {% include "dashboard_menu.html" with current="apply_goal" %}
{% endblock %}
{% block content %}
<h2>set your goal</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="set">
</form>
{% endblock %}

pullup/trainings/templates/chart.html
{% extends "dashboard_base.html" %}
{% block head_extensions %}
    <!-- for google chart -->
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Mushrooms', 3],
          ['Onions', 1],
          ['Olives', 1],
          ['Zucchini', 1],
          ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = {'title':'How Much Pizza I Ate Last Night',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
{% endblock %}
{% block menu %}
    {% include "dashboard_menu.html" with current="chart" %}
{% endblock %}
{% block content %}
<h2>training summary</h2>
<div id="chart_div"></div>
{% for training in trainings_done  %}
    {{ training }}
{% endfor %}

{% endblock %}

pullup/trainings/templates/dashboard.html
{% extends "dashboard_base.html" %}
{% block content %}
<div class="row">
    <div class="column"><h2>dashboard</h2>
        {% if request.user.player.goal %}<a class="button" href="{% url 'trainings:training_session' %}">start training</a>{% endif %}
        <a class="button" href="{% url 'trainings:apply_goal' %}">set your goal</a>
    </div>
    <div class="column">
        <h5>your goal</h5>
        <h3>{% if request.user.player.goal %}{{ request.user.player.goal }}{% endif %}</h3>
        <h5>your actual record</h5>
        <h3>{% if request.user.player.actual_record %}{{ request.user.player.actual_record }}{% endif %}</h3>
        <h5>last training sessions</h5>
        <ul>
            {% for session in sessions %}
                <li>{{ session.done_date }} <strong>{{ session.reps_done }} reps</strong></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

pullup/trainings/templates/dashboard_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

    <!-- CSS Reset -->
    <!--<link rel="stylesheet" href="bower_components/normalize.css/normalize.css">-->

    <!-- Milligram CSS minified -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.2.4/milligram.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block header_extensions %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}
        {% include "dashboard_menu.html" with current="dashboard" %}
    {% endblock %}
    {% if messages %}
    <blockquote>
        {% for message in messages %}
        <p><em>{{ message }}</em></p>
        {% endfor %}
    </blockquote>
    {% endif %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}
</div>
</body>
</html>

pullup/trainings/templates/dashboard_menu.html
<div class="row" style="margin-bottom: 15px;;">
    <div class="column column-75">
        <a class="button {% if current == 'dashboard' %}button-outline{% else %}button-clear {% endif %}" href="{% url 'trainings:dashboard' %}">Dashboard</a>
        <a class="button {% if current == 'training_session' %}button-outline{% else %}button-clear {% endif %}" href="{% url 'trainings:training_session' %}">Training session</a>
        <a class="button {% if current == 'apply_goal' %}button-outline{% else %}button-clear {% endif %}" href="{% url 'trainings:apply_goal' %}">Set goal</a>
        <a class="button {% if current == 'training_summary' %}button-outline{% else %}button-clear {% endif %}" href="{% url 'trainings:training_summary' %}">Training summary</a>
        <a class="button {% if current == 'chart' %}button-outline{% else %}button-clear {% endif %}" href="{% url 'trainings:chart' %}">Chart</a>
    </div>
    <div class="column column-25 pull-right">
        <span>welcome {{ request.user }}</span>
        <a class="button button-clear" href="{% url 'logout' %}">Logout</a>
    </div>
</div>

pullup/trainings/templates/footer.html
<div>
    <div class="float-left">
        app made for educational purposes<br>
        <a href="https://bitbucket.org/grzch/">Grzegorz Szymborski</a>
    </div>
    <div class="float-right">
        <p>
            © 2016 Politchnika Warszawska, Electrical Engineering
        </p>
    </div>
</div>

pullup/trainings/templates/register_player.html
{% extends "base.html" %}
{% block content %}
<h2>set your goal</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="register">
</form>
{% endblock %}

pullup/trainings/templates/training_session.html
{% extends "dashboard_base.html" %}
{% block menu %}
{% include "dashboard_menu.html" with current="training_session" %}
{% endblock %}
{% block content %}
<style>
    .pullups-reps{
        width: 40px;
        display: inline-block;
    }

    input.pullups-reps-input{
        display: none;
        width: auto;
    }
</style>
<h2>training session</h2>
<h3>reps in series</h3>
<p>Take breaks from <strong>30 to 60</strong> seconds between series</p>
<ol>
    {% for serie in session.series %}
        <li><h3 class="pullups-reps">{{ serie }}</h3>
    {% endfor %}

</ol>
<form action="." method="POST">
    {% csrf_token %}
    <input type="number" class="pullups-reps-input" id="cantInput" name="reps_done" placeholder="reps made">
    <input type="submit" value="&#10003; done" class="button" href="{% url 'trainings:training_summary' %}"/> <a class="button button-clear" href="#" id="cantButton">&#10060; can't</a></li>
</form>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function (){
        // show input for reps made after can't button click
        $('#cantButton').click(function(event){
            event.preventDefault();
            $('#cantInput').show();
            event.target.remove();
        });
    });

</script>
{% endblock %}

pullup/trainings/templates/training_summary.html
{% extends "dashboard_base.html" %}
{% block menu %}
    {% include "dashboard_menu.html" with current="training_summary" %}
{% endblock %}
{% block content %}
<h2>training summary</h2>
{% if not last_training %}
    <p>there is no informations about your training</p>
{% else %}
    {% if not last_training.completed %}
        <p>next time your training will be fitted to your exhaustion</p>
    {% endif %}
        you have done <h4>{{ last_training.reps_done }} reps</h4>
        you should train again in <h4>2 days</h4>

    total done <h4>{{ request.user.player.reps_done }} reps</h4>
    total sessions <h4>{{ request.user.player.sessions_done_number }}</h4>
{% endif %}





{% endblock %}